# Generated by Django 5.2.5 on 2025-08-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=13),
        ),
    ]
