services:
  - type: web
    name: madozin-portfolio   # change if you want another name
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "gunicorn wsgi:application --chdir /opt/render/project/src/portfolio"

